os: unstable
install:
  - git submodule update --init --recursive
  - choco install InnoSetup
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - echo Running Inno Setup
  - iscc JokerSetup.iss
  - dir