os: unstable

install:
  - git submodule update --init --recursive
  - choco install -y InnoSetup
  - set PATH=C:\Program Files (x86)\Inno Setup 5;%PATH%

build_script:
  - echo Building..
  - build --clean
  - dir

artifacts:
  - path: dist\*.exe
    name: installer

deploy:
  provider: Environment
  name: GitHub
  on:
    branch: master
    appveyor_repo_tag: true