os: unstable
install:
  - git submodule update --init --recursive
  - choco install -y InnoSetup
  - set PATH=C:\Program Files (x86)\Inno Setup 5;%PATH%
build_script:
  - echo Building..
  - build --clean --build %APPVEYOR_BUILD_NUMBER%
  - dir
deploy:
  provider: Environment
  name: GitHub
